version: '3.8'

services:
  # PostgreSQL database service
  postgres:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/postgres-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  # Backend application service
  backend:
    build:
      context: ./backend   # Path to your backend application Dockerfile
      dockerfile: Dockerfile
    container_name: my_backend
    environment:
      DATABASE_URL: postgresql://my_user:my_password@postgres:5432/my_database
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    env_file:
      - .env

volumes:
  postgres_data:

